name: autofix.ci
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  format-r:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: rstudio/shiny-workflows/format-r-code@v1
    - name: commit fixes, if any
      uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
# autofix.ci recommends pinning to a commit hash for security
