name: R CMD check package

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-package:
    strategy:
      matrix:
        r-version: ["4.4.0", "release"]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on:  ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r-version}}
        use-public-rspm: true
    - name: "Set up dependencies for wwinference"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        needs: check
    - name: "Check forecastools package"
      uses: r-lib/actions/check-r-package@v2
      with:
        error-on: '"warning"'
        build_args: 'c("--no-manual", "--no-build-vignettes")'
        args: 'c("--no-manual", "--as-cran", "--ignore-vignettes")'
